"""empty message

Revision ID: 503d55ad4ea1
Revises: 
Create Date: 2020-05-07 16:45:55.922389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503d55ad4ea1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('quiz_name', sa.String(length=128), nullable=True),
    sa.Column('removed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('quiz_id')
    )
    op.create_index(op.f('ix_quiz_quiz_name'), 'quiz', ['quiz_name'], unique=False)
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('question',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.Column('youtube_link', sa.String(length=256), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('correct_answer', sa.String(length=256), nullable=True),
    sa.Column('option_1', sa.String(length=256), nullable=True),
    sa.Column('option_2', sa.String(length=256), nullable=True),
    sa.Column('option_3', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.quiz_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_index(op.f('ix_question_question_id'), 'question', ['question_id'], unique=False)
    op.create_table('results',
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('user_answer', sa.String(length=256), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.question_id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.quiz_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_index(op.f('ix_results_result_id'), 'results', ['result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_results_result_id'), table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_question_question_id'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_quiz_quiz_name'), table_name='quiz')
    op.drop_table('quiz')
    # ### end Alembic commands ###
