"""users table

Revision ID: c2740a8065da
Revises: 503d55ad4ea1
Create Date: 2020-05-08 03:52:59.522199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2740a8065da'
down_revision = '503d55ad4ea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz', sa.Column('quiz_image', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_quiz_quiz_image'), 'quiz', ['quiz_image'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_quiz_image'), table_name='quiz')
    op.drop_column('quiz', 'quiz_image')
    # ### end Alembic commands ###
